# Generated by Django 4.2.4 on 2024-10-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='os_name',
            field=models.CharField(blank=True, help_text='Nome associado à Ordem de Serviço', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='os_number',
            field=models.CharField(blank=True, help_text='Número da Ordem de Serviço', max_length=50),
        ),
    ]
