# Generated by Django 4.2.4 on 2024-10-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_os_name_item_os_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='observation',
        ),
    ]
