# Generated by Django 4.2.4 on 2024-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_image_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='Indica se o usuário autorizou o avanço para a etapa sistama'),
        ),
    ]
