# Generated by Django 4.2.4 on 2025-03-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_is_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bot_error_message',
            field=models.TextField(blank=True, help_text='Mensagem de erro do bot, se houver', null=True),
        ),
    ]
