# Generated by Django 4.2.4 on 2025-05-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='robotalert',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
