# Generated by Django 4.2.4 on 2024-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
