# Generated by Django 4.2.4 on 2024-10-08 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_shift_result_item_sismama_result_item_stage'),
        ('tasks', '0001_initial'),
        ('values', '0002_alter_value_value_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.CharField(blank=True, max_length=100, null=True)),
                ('os_number', models.CharField(max_length=50)),
                ('cartao_sus', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_paciente', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('raca_etinia', models.CharField(blank=True, max_length=50, null=True)),
                ('idade_paciente', models.IntegerField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_coleta', models.DateField(blank=True, null=True)),
                ('data_liberacao', models.DateField(blank=True, null=True)),
                ('tamanho_lesao', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristica_lesao', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacao_lesao', models.CharField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_residencial', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_data', to='items.item')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_data', to='tasks.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
