# Generated by Django 4.2.4 on 2024-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0004_shiftdata_shift_result_shiftdata_sismama_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftdata',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shiftdata',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shiftdata',
            name='numero_residencial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shiftdata',
            name='raca_etinia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shiftdata',
            name='sexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shiftdata',
            name='tamanho_lesao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
