# Generated by Django 4.2.4 on 2025-05-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0005_alter_shiftdata_codigo_postal_alter_shiftdata_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdata',
            name='recipiente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
