# Generated by Django 4.2.4 on 2025-05-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_bot_error_message'),
        ('values', '0006_shiftdata_recipiente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftdata',
            unique_together={('item',)},
        ),
    ]
