# Generated by Django 4.2.4 on 2024-09-30 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('platform', models.CharField(choices=[('UIPATH', 'Uipath'), ('AUTOMATION_ANYWHERE', 'Automation Anywhere'), ('BLUEPRISM', 'Blueprism'), ('POWER_AUTOMATE', 'Power Automate'), ('PYTHON', 'Python'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=50)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
