# Generated by Django 4.2.4 on 2024-10-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('items', '0004_item_shift_result_item_sismama_result_item_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame_histopatologico', models.CharField(blank=True, max_length=255, null=True)),
                ('apresenta_risco_elevado_para_cancer_de_mama', models.CharField(blank=True, max_length=255, null=True)),
                ('gravida_ou_amamentando', models.CharField(blank=True, max_length=255, null=True)),
                ('tratamento_anterior_para_cancer', models.CharField(blank=True, max_length=255, null=True)),
                ('deteccao_da_lesao', models.CharField(blank=True, max_length=255, null=True)),
                ('mama', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacao_lesao', models.CharField(blank=True, max_length=255, null=True)),
                ('tamanho_lesao', models.CharField(blank=True, max_length=255, null=True)),
                ('caracteristica_lesao', models.TextField(blank=True, null=True)),
                ('material_enviado_procedente_de', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to='items.item')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to='tasks.task')),
            ],
        ),
    ]
